services:
  gitpatrol:
    image: efinityhub/gitpatrol:latest
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/var/lib/gitpatrol
    stop_grace_period: 35s
    restart: unless-stopped
